---
- name: "Create CKAN user"
  become: "yes"
  become_user: "postgres"
  postgresql_user:
    name:     "{{ ckan_db.ckan.user }}"
    password: "{{ ckan_db.ckan.pass }}"
    role_attr_flags: "LOGIN"

- name: "Create datastore user"
  become: "yes"
  become_user: "postgres"
  postgresql_user:
    name:     "{{ ckan_db.datastore.user }}"
    password: "{{ ckan_db.datastore.pass }}"
    role_attr_flags: "LOGIN"

- name: "Create CKAN database"
  become: "yes"
  become_user: "postgres"
  postgresql_db:
    name:  "{{ ckan_db.ckan.name }}"
    owner: "{{ ckan_db.ckan.user }}"
  register: "ckan_database"

- name: "Create datastore database"
  become: "yes"
  become_user: "postgres"
  postgresql_db:
    name:  "{{ ckan_db.datastore.name }}"
    owner: "{{ ckan_db.ckan.user      }}"

- name: "Generate database permissions"
  shell: "./bin/paster --plugin=ckan datastore set-permissions -c {{ ckan_path }}/etc/production.ini > permissions.sql"
  args:
    chdir:   "{{ ckan_path }}"
  when: "ckan_database.changed"

- name: "Apply database permissions"
  become: "yes"
  become_user: "postgres"
  shell: "psql -v ON_ERROR_STOP=1 < permissions.sql"
  args:
    chdir: "{{ ckan_path }}"
  when: "ckan_database.changed"
...
