---
- name: "Create solr core"
  become_user: "solr"
  command: "{{ solr_install_dir }}/solr/bin/solr create -c ckan"
  args:
    creates: "{{ solr_home }}/data/ckan/conf/solrconfig.xml"

- name: "Install Solr config"
  copy:
    src: "solr-7/solrconfig.xml"
    dest: "{{ solr_home }}/data/ckan/conf/solrconfig.xml"
    owner: "solr"
    group: "solr"
  notify: "solr_restart"

- name: "Install Solr schema"
  copy:
    src: "solr-7/schema.xml"
    dest: "{{ solr_home }}/data/ckan/conf/schema.xml"
    owner: "solr"
    group: "solr"
  notify: "solr_restart"
...
