---
- name: "Create solr core"
  become_user: "solr"
  command: "{{ solr_install_dir }}/solr/bin/solr create -c ckan"
  args:
    creates: "{{ solr_home }}/data/ckan/conf/solrconfig.xml"

- name: "Disable managed schema"
  xml:
    path: "{{ solr_home }}/data/ckan/conf/solrconfig.xml"
    xpath: "/config/schemaFactory"
    attribute: "class"
    value: "ClassicIndexSchemaFactory"
    state: "present"
  notify: "solr_restart"

- name: "Remove defaultSearchField"
  xml:
    path: "{{ ckan_path }}/src/ckan/ckan/config/solr/schema.xml"
    xpath: "/schema/defaultSearchField"
    state: "absent"
  notify: "solr_restart"

- name: "Add DF element"
  xml:
    path: "{{ ckan_path }}/src/ckan/ckan/config/solr/schema.xml"
    xpath: "/schema/df"
    value: "text"
  notify: "solr_restart"

- name: "Remove solrQueryParser:defaultOperator"
  xml:
    path: "{{ ckan_path }}/src/ckan/ckan/config/solr/schema.xml"
    xpath: "/schema/solrQueryParser"
    attribute: "defaultOperator"
    state: "absent"
  notify: "solr_restart"

- name: "Add solrQueryParser:q.op"
  xml:
    path: "{{ ckan_path }}/src/ckan/ckan/config/solr/schema.xml"
    xpath: "/schema/solrQueryParser"
    attribute: "q.op"
    value: "AND"
  notify: "solr_restart"

- name: "Install solr schema"
  become_user: "solr"
  file:
    src:  "{{ ckan_path }}/src/ckan/ckan/config/solr/schema.xml"
    dest: "{{ solr_home }}/data/ckan/conf/schema.xml"
    state: "link"
  notify: "solr_restart"
...
