---
- name: Check for Solr core
  become_user: solr
  command: "{{ solr_install_dir }}/solr/bin/solr create -c ckan -d basic_configs
            creates={{ solr_home }}/data/ckan/conf/solrconfig.xml"
  tags: solr

- name: Make sure solr is set to use Schema.xml
  become_user: solr
  copy:
    src: solrconfig.xml
    dest: "{{ solr_home }}/data/ckan/conf/solrconfig.xml"
  tags: solr

- name: Install CKAN schema.xml
  become_user: solr
  copy:
    remote_src: True
    src: "{{ ckan_path }}/src/ckan/ckan/config/solr/schema.xml"
    dest: "{{ solr_home }}/data/ckan/conf/schema.xml"
    force: no
  notify: restart solr
  tags: solr

- name: Point CKAN to Solr
  lineinfile:
    dest: "{{ ckan_path }}/etc/production.ini"
    regexp: 'solr_url'
    line: 'solr_url = http://127.0.0.1:8983/solr'
...
